(self.AMP=self.AMP||[]).push({n:"amp-accordion",ev:"0.1",l:true,v:"2103122145004",m:0,f:(function(AMP,_){
'use strict';var aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ca(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var e=b[c];if(e&&e.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ca(this);"function"===typeof Symbol&&Symbol("x");var m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var da={a:!0},p={};try{p.__proto__=da;n=p.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=m;function ea(){var a,b;this.promise=new Promise(function(c,e){a=c;b=e});this.resolve=a;this.reject=b};function r(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(e){return c}};var fa=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var t=self.AMP_CONFIG||{},ha=("string"==typeof t.cdnProxyRegex?new RegExp(t.cdnProxyRegex):t.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function u(a){if(self.document&&self.document.head&&(!self.location||!ha.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}t.cdnUrl||u("runtime-host");t.geoApiUrl||u("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var v=self.__AMP_LOG;function w(){if(!v.user)throw Error("failed to call initLogConstructor");return v.user}function x(){if(v.dev)return v.dev;throw Error("failed to call initLogConstructor");}function y(a,b,c){w().assert(a,b,c,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function z(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return A(a,b)}function ia(a){a=B(a);a=B(a);a=a.isSingleDoc()?a.win:a;return C(a,"action")?A(a,"action"):null}function B(a){return a.nodeType?z((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function A(a,b){C(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function C(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var D={bubbles:!0,cancelable:!0};function ja(a,b,c){for(;a&&a!==c;a=a.parentElement)if(b(a))return a;return null};function E(a,b,c,e){var d=new F(a,b,c,e);return d.solveYValueFromXValue.bind(d)}function F(a,b,c,e){this.y0=this.x0=0;this.x1=a;this.y1=b;this.x2=c;this.y2=e;this.y3=this.x3=1}F.prototype.solveYValueFromXValue=function(a){return this.getPointY(this.solvePositionFromXValue(a))};
F.prototype.solvePositionFromXValue=function(a){var b=(a-this.x0)/(this.x3-this.x0);if(0>=b)return 0;if(1<=b)return 1;for(var c=0,e=1,d=0,f=0;8>f;f++){d=this.getPointX(b);var g=(this.getPointX(b+1E-6)-d)/1E-6;if(1E-6>Math.abs(d-a))return b;if(1E-6>Math.abs(g))break;else d<a?c=b:e=b,b-=(d-a)/g}for(f=0;1E-6<Math.abs(d-a)&&8>f;f++)d<a?(c=b,b=(b+e)/2):(e=b,b=(b+c)/2),d=this.getPointX(b);return b};
F.prototype.getPointX=function(a){if(0==a)return this.x0;if(1==a)return this.x3;var b=this.lerp(this.x0,this.x1,a),c=this.lerp(this.x1,this.x2,a),e=this.lerp(this.x2,this.x3,a);b=this.lerp(b,c,a);c=this.lerp(c,e,a);return this.lerp(b,c,a)};F.prototype.getPointY=function(a){if(0==a)return this.y0;if(1==a)return this.y3;var b=this.lerp(this.y0,this.y1,a),c=this.lerp(this.y1,this.y2,a),e=this.lerp(this.y2,this.y3,a);b=this.lerp(b,c,a);c=this.lerp(c,e,a);return this.lerp(b,c,a)};
F.prototype.lerp=function(a,b,c){return a+c*(b-a)};var ka=E(.25,.1,.25,1),la=E(.42,0,1,1),ma=E(0,0,.58,1),na=E(.42,0,.58,1),oa={linear:function(a){return a},ease:ka,"ease-in":la,"ease-out":ma,"ease-in-out":na};
function G(a){if(!a)return null;if("string"==typeof a){if(-1!=a.indexOf("cubic-bezier")){var b=a.match(/cubic-bezier\((.+)\)/);if(b&&(b=b[1].split(",").map(parseFloat),4==b.length)){for(var c=0;4>c;c++)if(isNaN(b[c]))return null;return E(b[0],b[1],b[2],b[3])}return null}return oa[a]}return a};function pa(){}function H(a){this.A=a;this.D=z(self,"vsync");this.I=null;this.h=[]}function qa(a,b,c){var e=ra;return(new H(a)).setCurve(e).add(0,b,1).start(c)}H.prototype.setCurve=function(a){a&&(this.I=G(a));return this};H.prototype.add=function(a,b,c,e){this.h.push({delay:a,func:b,duration:c,curve:G(e)});return this};H.prototype.start=function(a){return new I(this.D,this.A,this.h,this.I,a)};
function I(a,b,c,e,d){this.D=a;this.A=b;this.h=[];for(b=0;b<c.length;b++){var f=c[b];this.h.push({delay:f.delay,func:f.func,duration:f.duration,curve:f.curve||e,started:!1,completed:!1})}this.O=d;this.T=Date.now();this.F=!0;this.L={};c=new ea;this.K=c.promise;this.S=c.resolve;this.R=c.reject;this.M=this.D.createAnimTask(this.A,{mutate:this.U.bind(this)});this.D.canAnimate(this.A)?this.M(this.L):(x().warn("Animation","cannot animate"),J(this,!1,0))}
I.prototype.then=function(a,b){return a||b?this.K.then(a,b):this.K};I.prototype.thenAlways=function(a){a=a||pa;return this.then(a,a)};I.prototype.halt=function(a){J(this,!1,a||0)};function J(a,b,c){if(a.F){a.F=!1;if(0!=c){1<a.h.length&&a.h.sort(function(d,f){return d.delay+d.duration-(f.delay+f.duration)});try{if(0<c)for(c=0;c<a.h.length;c++)a.h[c].func(1,!0);else for(var e=a.h.length-1;0<=e;e--)a.h[e].func(0,!1)}catch(d){x().error("Animation","completion failed: "+d,d),b=!1}}b?a.S():a.R()}}
I.prototype.U=function(){if(this.F){for(var a=Date.now(),b=Math.min((a-this.T)/this.O,1),c=0;c<this.h.length;c++){var e=this.h[c];!e.started&&b>=e.delay&&(e.started=!0)}for(c=0;c<this.h.length;c++)if(e=this.h[c],e.started&&!e.completed)a:{var d;if(0<e.duration){var f=d=Math.min((b-e.delay)/e.duration,1);if(e.curve&&1!=f)try{f=e.curve(d)}catch(g){x().error("Animation","step curve failed: "+g,g);J(this,!1,0);break a}}else f=d=1;1==d&&(e.completed=!0);try{e.func(f,e.completed)}catch(g){x().error("Animation",
"step mutate failed: "+g,g),J(this,!1,0)}}1==b?J(this,!0,0):this.D.canAnimate(this.A)?this.M(this.L):(x().warn("Animation","cancel animation"),J(this,!1,0))}};var L,M="Webkit webkit Moz moz ms O o".split(" ");function N(a,b,c){if(b.startsWith("--"))return b;L||(L=Object.create(null));var e=L[b];if(!e||c){e=b;if(void 0===a[b]){var d=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var f=0;f<M.length;f++){var g=M[f]+d;if(void 0!==a[g]){d=g;break a}}d=""}var h=d;void 0!==a[h]&&(e=h)}c||(L[b]=e)}return e}function O(a,b,c){(b=N(a.style,b,void 0))&&(b.startsWith("--")?a.style.setProperty(b,c):a.style[b]=c)}function P(a,b){for(var c in b)O(a,c,b[c])};function Q(a,b){return function(c,e){for(var d in b){var f=d;"display"===f&&x().error("STYLE","`display` style detected. You must use toggle instead.");O(a,f,b[d](c,e))}}}function R(a,b){return function(c){return a+(b-a)*c}}function S(a){return function(b){return a(b)+"px"}};var sa=E(.47,0,.745,.715),ra=E(.39,.575,.565,1);
function ta(a){if(a.__AMP__EXPERIMENT_TOGGLES)var b=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);b=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var c in a.AMP_CONFIG){var e=a.AMP_CONFIG[c];"number"===typeof e&&0<=e&&1>=e&&(b[c]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(c=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){e=e.getAttribute("content").split(",");
for(var d=0;d<e.length;d++)-1!=c.indexOf(e[d])&&(b[e[d]]=!0)}c=Object;e=c.assign;d="";try{"localStorage"in a&&(d=a.localStorage.getItem("amp-experiment-toggles"))}catch(h){x().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}d=d?d.split(/\s*,\s*/g):[];for(var f=Object.create(null),g=0;g<d.length;g++)0!=d[g].length&&("-"==d[g][0]?f[d[g].substr(1)]=!1:f[d[g]]=!0);e.call(c,b,f);if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){c=
a.AMP_CONFIG["allow-url-opt-in"];d=a.location.originalHash||a.location.hash;e=Object.create(null);if(d)for(;g=fa.exec(d);)f=r(g[1],g[1]),g=g[2]?r(g[2].replace(/\+/g," "),g[2]):"",e[f]=g;for(d=0;d<c.length;d++)f=e["e-"+c[d]],"1"==f&&(b[c[d]]=!0),"0"==f&&(b[c[d]]=!1)}}return!!b["amp-accordion-display-locking"]&&void 0!==a.document.body.onbeforematch}
function T(a){var b=AMP.BaseElement.call(this,a)||this;b.C=[];b.G=null;b.B=null;b.H=!1;b.o=null;b.j=null;b.J=a.id?a.id:Math.floor(100*Math.random());return b}var U=AMP.BaseElement;T.prototype=aa(U.prototype);T.prototype.constructor=T;if(q)q(T,U);else for(var V in U)if("prototype"!=V)if(Object.defineProperties){var W=Object.getOwnPropertyDescriptor(U,V);W&&Object.defineProperty(T,V,W)}else T[V]=U[V];T.W=U.prototype;T.prerenderAllowed=function(){return!0};
T.prototype.isLayoutSupported=function(a){return"container"==a};
T.prototype.buildCallback=function(){var a=this;this.j=ia(this.element);this.H=this.element.hasAttribute("disable-session-states");this.G=ua(this);this.B=va(this);this.o=this.getRealChildren();this.o.forEach(function(b,c){y("section"==b.tagName.toLowerCase(),"Sections should be enclosed in a <section> tag, See https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md. Found in: %s",a.element);var e=b.children;y(2==e.length,"Each section must have exactly two children. See https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md. Found in: %s",
a.element);var d=e["0"],f=e["1"];f.classList.add("i-amphtml-accordion-content");var g=f.getAttribute("id");g||(g=a.J+"_AMP_content_"+c,f.setAttribute("id",g));var h=d.getAttribute("id");h||(h=a.J+"_AMP_header_"+c,d.setAttribute("id",h));a.registerAction("toggle",function(k){return X(a,k)});a.registerAction("expand",function(k){return X(a,k)});a.registerAction("collapse",function(k){return X(a,k)});a.j.addToAllowlist("amp-accordion",["toggle","expand","collapse"],["email"]);(new a.win.MutationObserver(function(k){wa(a,
k)})).observe(b,{attributes:!0,attributeFilter:["data-expand"]});a.B[g]?b.setAttribute("expanded",""):!1===a.B[g]&&b.removeAttribute("expanded");a.mutateElement(function(){});var l=b.hasAttribute("expanded");d.classList.add("i-amphtml-accordion-header");d.hasAttribute("role")||d.setAttribute("role","button");d.setAttribute("aria-controls",g);d.setAttribute("aria-expanded",String(l));d.hasAttribute("tabindex")||d.setAttribute("tabindex",0);a.C.push(d);f.setAttribute("aria-labelledby",h);f.hasAttribute("role")||
f.setAttribute("role","region");y(0==a.j.hasAction(d,"tap",b),"amp-accordion headings should not have tap actions registered.");d.addEventListener("click",a.N.bind(a));d.addEventListener("keydown",a.P.bind(a));ta(a.win)&&(a.element.classList.add("i-amphtml-display-locking"),f.addEventListener("beforematch",function(){Y(a,b,3,!0)}))})};
function X(a,b){var c=b.method,e=b.args,d=b.trust,f=void 0;"expand"===c?f=!0:"collapse"===c&&(f=!1);if(e){var g=e.section,h=a.getAmpDoc().getElementById(g);h=w().assertElement(h);y(h,"No element found with id: %s",g);Y(a,h,d,f)}else for(c=0;c<a.o.length;c++)Y(a,a.o[c],d,f)}function ua(a){var b=a.element.id||a.element.getResourceId();a=a.win.location.href;var c=a.indexOf("#");a=-1==c?a:a.substring(0,c);return"amp-"+b+"-"+a}
function va(a){if(a.H)return{};try{var b=a.win.sessionStorage.getItem(a.G);return b?JSON.parse(b):{}}catch(c){return x().fine("AMP-ACCORDION","Error setting session state: %s, %s",c.message,c.stack),{}}}function xa(a){if(!a.H){var b=JSON.stringify(a.B);try{a.win.sessionStorage.setItem(a.G,b)}catch(c){x().fine("AMP-ACCORDION","Error setting session state: %s, %s",c.message,c.stack)}}}
function Z(a,b,c,e){var d=a.win;var f="accordionSection."+b;var g={};var h={detail:g};Object.assign(h,void 0);"function"==typeof d.CustomEvent?f=new d.CustomEvent(f,h):(d=d.document.createEvent("CustomEvent"),d.initCustomEvent(f,!!h.bubbles,!!h.cancelable,g),f=d);a.j.trigger(c,b,f,e);a=a.element;c=a.ownerDocument.createEvent("Event");c.data={};c.initEvent(b,D.bubbles,D.cancelable);a.dispatchEvent(c)}
function Y(a,b,c,e){var d=b.children,f=d[0];d=d[1].getAttribute("id");var g=b.hasAttribute("expanded"),h=void 0==e?!b.hasAttribute("expanded"):e;h&&b.hasAttribute("expanded")||!h&&!b.hasAttribute("expanded")||(a.element.hasAttribute("animate")?h?(f.setAttribute("aria-expanded","true"),ya(a,b,c),a.element.hasAttribute("expand-single-section")&&a.o.forEach(function(l){l!=b&&(za(a,l,c),l.children[0].setAttribute("aria-expanded","false"))})):(f.setAttribute("aria-expanded","false"),za(a,b,c)):a.mutateElement(function(){h?
(Z(a,"expand",b,c),b.setAttribute("expanded",""),f.setAttribute("aria-expanded","true"),a.element.hasAttribute("expand-single-section")&&a.o.forEach(function(l){l!=b&&(l.hasAttribute("expanded")&&(Z(a,"collapse",l,c),l.removeAttribute("expanded")),l.children[0].setAttribute("aria-expanded","false"))})):(Z(a,"collapse",b,c),b.removeAttribute("expanded"),f.setAttribute("aria-expanded","false"))},b),a.B[d]=!g,xa(a))}
function ya(a,b,c){var e,d,f,g,h,l=b.children[1];a.measureMutateElement(function(){e=b.offsetWidth;var k=N(l.style,"width",void 0);h=k?k.startsWith("--")?l.style.getPropertyValue(k):l.style[k]:void 0},function(){var k={position:"fixed",width:e+"px",opacity:"0"},ba=l.style,K;for(K in k)ba.setProperty(N(ba,K),k[K].toString(),"important");b.hasAttribute("expanded")||b.setAttribute("expanded","")}).then(function(){return a.measureMutateElement(function(){d=b.offsetHeight;f=l.offsetHeight;var k=a.getViewport().getHeight();
g=Aa(Math.abs(f),k)},function(){P(b,{overflow:"hidden",height:d+"px"});P(l,{position:"",opacity:"",width:h})})}).then(function(){var k=new H(a.element);k.setCurve(sa);k.add(0,Q(b,{height:S(R(d,d+f))}),1);k.add(0,Q(l,{opacity:R(0,1)}),1);return k.start(g).thenAlways(function(){a.mutateElement(function(){Z(a,"expand",b,c);P(b,{overflow:"",height:""});P(l,{opacity:""})})})})}
function za(a,b,c){var e,d,f,g=b.firstElementChild;a.measureMutateElement(function(){e=b.offsetHeight;d=g.offsetHeight;var h=a.getViewport().getSize().height;f=Aa(Math.abs(e),h)},function(){P(b,{overflow:"hidden"})}).then(function(){return qa(b,Q(b,{height:S(R(e,d))}),f).thenAlways(function(){return a.mutateElement(function(){b.hasAttribute("expanded")&&(Z(a,"collapse",b,c),b.removeAttribute("expanded"));P(b,{height:"",overflow:""})})})})}
function Aa(a,b){var c=void 0===c?200:c;var e=void 0===e?500:e;return Math.min(Math.max(Math.abs(a)/b*e,c),e)}T.prototype.N=function(a){Ba(this,a)&&(a.preventDefault(),Y(this,a.currentTarget.parentElement,3))};function Ba(a,b){var c=b.target;b=b.currentTarget;var e=!!ja(c,function(f){return"A"==f.tagName},b),d=a.j.hasAction(c,"tap",b);return!e&&!d}
T.prototype.P=function(a){if(!a.defaultPrevented)switch(a.key){case "ArrowUp":case "ArrowDown":var b=this.C.indexOf(a.currentTarget);if(-1!==b){a.preventDefault();a=(b+("ArrowUp"==a.key?-1:1))%this.C.length;0>a&&(a+=this.C.length);try{this.C[a].focus()}catch(c){}}break;case "Enter":case " ":a.target==a.currentTarget&&(a.preventDefault(),Y(this,a.currentTarget.parentElement,3))}};
function wa(a,b){b.forEach(function(c){var e=c.target,d=e.hasAttribute("data-expand");e.hasAttribute("expanded")!==d&&Y(a,e,2,d)})}T.prototype.V=function(){return this.j};(function(a){a.registerElement("amp-accordion",T,"amp-accordion>section>:last-child{display:none!important}amp-accordion>section[expanded]>:last-child{display:block!important}.i-amphtml-accordion-content,.i-amphtml-accordion-header{margin:0}.i-amphtml-accordion-header{cursor:pointer;background-color:#efefef;padding-right:20px;border:1px solid #dfdfdf}amp-accordion.i-amphtml-display-locking>section:not([expanded])>:last-child,amp-accordion.i-amphtml-display-locking>section:not([expanded])>:last-child *{content-visibility:hidden-matchable!important;display:block!important}amp-accordion>section:not([expanded]) .i-amphtml-media-component,amp-accordion>section:not([expanded]) .i-amphtml-media-component *{display:none!important;visibility:hidden!important}\n/*# sourceURL=/extensions/amp-accordion/0.1/amp-accordion.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-accordion-0.1.js.map
