(self.AMP=self.AMP||[]).push({n:"amp-bind",ev:"0.1",l:true,v:"2103122145004",m:0,f:(function(AMP,_){
'use strict';var m,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return d}return function(){throw Error("Cannot find global object");}()}var ca=ba(this);"function"===typeof Symbol&&Symbol("x");var da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={a:!0},ha={};try{ha.__proto__=fa;ea=ha.a;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function q(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ma=b.prototype};function ja(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var ka=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function la(a){var b=Object.create(null);if(!a)return b;for(var c;c=ka.exec(a);){var d=ja(c[1],c[1]),e=c[2]?ja(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var ma="";
function r(){var a=self;if(a.__AMP_MODE)var b=a.__AMP_MODE;else{b=la(a.location.originalHash||a.location.hash);var c=la(a.location.search);ma||(ma=a.AMP_CONFIG&&a.AMP_CONFIG.v?a.AMP_CONFIG.v:"012103122145004");b={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(b.development)||a.AMP_DEV_MODE),examiner:"2"==b.development,esm:!1,geoOverride:b["amp-geo"],minified:!0,lite:void 0!=c.amp_lite,test:!1,log:b.log,version:"2103122145004",rtvVersion:ma};b=a.__AMP_MODE=b}return b}
;var na=Object.prototype.toString;function v(a){return a?Array.prototype.slice.call(a):[]}function x(a){return"[object Object]"===na.call(a)};var y=self.AMP_CONFIG||{},oa=("string"==typeof y.cdnProxyRegex?new RegExp(y.cdnProxyRegex):y.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function pa(a){if(!self.document||!self.document.head||self.location&&oa.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var z={thirdParty:y.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:y.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof y.thirdPartyFrameRegex?new RegExp(y.thirdPartyFrameRegex):y.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:y.cdnUrl||pa("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:oa,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:y.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:y.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:y.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:y.geoApiUrl||pa("amp-geo-api")};function qa(a){var b=Object.getOwnPropertyDescriptor(a,"message");if(b&&b.writable)return a;var c=a.stack,d=Error(a.message),e;for(e in a)d[e]=a[e];d.stack=c;return d}self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var A=self.__AMP_LOG;function C(){if(!A.user)throw Error("failed to call initLogConstructor");return A.user}function D(){if(A.dev)return A.dev;throw Error("failed to call initLogConstructor");}
function E(a,b,c){return C().assert(a,b,c,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function ra(a){a?-1==a.indexOf("\u200b\u200b\u200b")&&(a+="\u200b\u200b\u200b"):a="\u200b\u200b\u200b";a=Error.call(this,a);this.message=a.message;"stack"in a&&(this.stack=a.stack)}q(ra,Error);
function sa(a,b,c,d){if(!b){var e=Array.prototype.slice.call(arguments,3),f=[],g,h=(c||"Assertion failed").replace(/%s/g,function(){var k=e.shift();""!=k&&f.push(k);g||1!=(null==k?void 0:k.nodeType)||(g=k);return 1==(null==k?void 0:k.nodeType)?k.tagName.toLowerCase()+(k.id?"#"+k.id:""):k});h=new a(h);h.messageArray=f;g&&(h.associatedElement=g,g.classList.add("i-amphtml-error"));throw h;}}function F(a,b,c,d,e){sa(ra,a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};var ta=Object.prototype.hasOwnProperty;function G(a){var b=Object.create(null);a&&Object.assign(b,a);return b}function H(a){return a||{}}function I(a,b){if(ta.call(a,b))return a[b]}
function ua(a,b){var c=[],d=[];d.push({t:a,s:b,d:0});for(a={};0<d.length;){b=d.shift();a.G=b.t;a.C=b.s;a.P=b.d;if(c.includes(a.C))throw Error("Source object has a circular reference.");c.push(a.C);a.G!==a.C&&(10<a.P?Object.assign(a.G,a.C):Object.keys(a.C).forEach(function(e){return function(f){var g=e.C[f];if(ta.call(e.G,f)){var h=e.G[f];if(x(g)&&x(h)){d.push({t:h,s:g,d:e.P+1});return}}e.G[f]=g}}(a)));a={C:a.C,G:a.G,P:a.P}}};function J(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function K(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return L(a,b)}function M(a,b){var c=N(a);c=O(c);return L(c,b)}function va(a,b){a=N(a);a=O(a);return wa(a,b)?L(a,b):null}function N(a){return a.nodeType?K((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function O(a){a=N(a);return a.isSingleDoc()?a.win:a}function L(a,b){wa(a,b);a=P(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function xa(a,b,c,d){var e=P(a),f=e[c];f||(f=e[c]={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null,sharedInstance:!1});f.ctor||(f.ctor=d,f.context=b,f.sharedInstance=!1,f.resolve&&L(a,c))}function ya(a,b){var c=za(a,b);if(c)return c;a=P(a);a[b]=Aa();return a[b].promise}function za(a,b){var c=P(a)[b];if(c){if(c.promise)return c.promise;L(a,b);return c.promise=Promise.resolve(c.obj)}return null}function P(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}
function wa(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor)}function Aa(){var a=new J,b=a.promise,c=a.resolve;a=a.reject;b.catch(function(){});return{obj:null,promise:b,resolve:c,reject:a,context:null,ctor:null}};function Q(){this.wa=100;this.X=this.ba=0;this.R=Object.create(null)}Q.prototype.has=function(a){return!!this.R[a]};Q.prototype.get=function(a){var b=this.R[a];if(b)return b.access=++this.X,b.payload};Q.prototype.put=function(a,b){this.has(a)||this.ba++;this.R[a]={payload:b,access:this.X};if(!(this.ba<=this.wa)){D().warn("lru-cache","Trimming LRU cache");a=this.R;var c=this.X+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.ba--)}};var Ba=H({c:!0,v:!0,a:!0,ad:!0}),Ca,Fa,Ga=/[?&]amp_js[^&]*/,Ha=/[?&]amp_gsa[^&]*/,Ia=/[?&]amp_r[^&]*/,Ja=/[?&]amp_kit[^&]*/,Ka=/[?&]usqp[^&]*/;
function R(a){Ca||(Ca=self.document.createElement("a"),Fa=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new Q));var b=Fa,c=Ca;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a}
function La(a,b){var c=void 0===c?"source":c;F(null!=a,"%s %s must be available",b,c);var d=a;"string"==typeof d&&(d=R(d));var e;(e="https:"==d.protocol||"localhost"==d.hostname||"127.0.0.1"==d.hostname)||(d=d.hostname,e=d.length-10,e=0<=e&&d.indexOf(".localhost",e)==e);F(e||/^(\/\/)/.test(a),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,a)}
function S(a){"string"==typeof a&&(a=R(a));return z.cdnProxyRegex.test(a.origin)}
function Ma(a){"string"==typeof a&&(a=R(a));if(!S(a))return a.href;var b=a.pathname.split("/");F(Ba[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);F(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");d=(d=a.search)&&"?"!=d?(d=d.replace(Ga,"").replace(Ha,"").replace(Ia,"").replace(Ja,"").replace(Ka,"").replace(/^[?&]/,""))?"?"+d:"":"";return b+d+(a.hash||"")}
function Na(a,b){"string"==typeof b&&(b=R(b));if("function"==typeof URL)var c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=R(d));c=c.replace(/\\/g,"/");var e=R(c);c=c.toLowerCase().startsWith(e.protocol)?e.href:c.startsWith("//")?d.protocol+c:c.startsWith("/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}function Oa(a){var b=R(a),c=la(b.search);F(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};var Pa,Qa="Webkit webkit Moz moz ms O o".split(" ");function Ra(a){var b=!1;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function Sa(){return AMP.BaseElement.apply(this,arguments)||this}q(Sa,AMP.BaseElement);m=Sa.prototype;m.getLayoutPriority=function(){return 1};m.isAlwaysFixed=function(){return!0};m.isLayoutSupported=function(){return!0};m.renderOutsideViewport=function(){return!0};m.M=function(){return"<amp-bind-macro> "+(this.element.getAttribute("id")||"<unknown id>")};var Ta;function T(){return Ta?Ta:Ta=Promise.resolve(void 0)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var Ua=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function Va(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};function Wa(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}function Xa(a,b){return a.closest?a.closest(b):Wa(a,function(c){var d=c.matches||c.webkitMatchesSelector||c.mozMatchesSelector||c.msMatchesSelector||c.oMatchesSelector;return d?d.call(c,b):!1})}function Ya(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)}function Za(a){return"SCRIPT"==a.tagName&&a.hasAttribute("type")&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()}
function $a(a){a.tagName.startsWith("AMP-");if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new J;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};function ab(){var a=r().esm?".mjs":".js";var b=z.cdn;return b+"/rtv/"+r().rtvVersion+"/ww"+a}
function bb(a){if(!a)return[];for(var b=a.querySelectorAll("script[custom-element],script[custom-template]"),c=[],d=0;d<b.length;d++){var e=b[d],f=e.getAttribute("custom-element")||e.getAttribute("custom-template"),g;if(g=e.src){var h=g.match(/^(.*)\/(.*)-([0-9.]+|latest)(\.max)?\.(?:js|mjs)$/i);g=h?h[2]:void 0;h=h?h[3]:void 0;g=g&&h?{extensionId:g,extensionVersion:h}:null}else g=null;f&&g&&c.push({extensionId:f,extensionVersion:g.extensionVersion})}return c};function cb(a){var b=za(O(a),"bind");if(b)return b;var c=N(a);return c.waitForBodyOpen().then(function(){var d=c.win;return db(c.win.document.head)?K(d,"extensions").waitForExtension(d,"amp-bind"):T()}).then(function(){var d=c.win;return d.__AMP_EXTENDED_ELEMENTS&&d.__AMP_EXTENDED_ELEMENTS["amp-bind"]?ya(O(a),"bind"):null})}function eb(a){var b=va(a,"bind");return b?Promise.resolve(b):cb(a)}function db(a){return bb(a).some(function(b){return"amp-bind"==b.extensionId})};function fb(a,b){if("."==b)return a;b=b.split(".");for(var c=0;c<b.length;c++){var d=b[c];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}return a}function gb(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}}
function hb(a,b){if(!isFinite(20))throw Error("Invalid depth: 20");if(a===b)return!0;for(a=[{a:a,b:b,depth:20}];0<a.length;){var c=a.shift();b=c.a;var d=c.b;c=c.depth;if(0<c){if(typeof b!==typeof d)return!1;if(Array.isArray(b)&&Array.isArray(d)){if(b.length!==d.length)return!1;for(var e=0;e<b.length;e++)a.push({a:b[e],b:d[e],depth:c-1});continue}else if(b&&d&&"object"===typeof b&&"object"===typeof d){var f=Object.keys(b),g=Object.keys(d);if(f.length!==g.length)return!1;for(e=0;e<f.length;e++){var h=
f[e];a.push({a:b[h],b:d[h],depth:c-1})}continue}}if(b!==d)return!1}return!0};function ib(a,b,c){c=void 0===c?{}:c;var d=void 0===c.expr?".":c.expr,e=void 0===c.urlReplacement?0:c.urlReplacement,f=void 0===c.refresh?!1:c.refresh,g=void 0===c.xssiPrefix?void 0:c.xssiPrefix;La(b.getAttribute("src"),b);var h=K(a.win,"batched-xhr");return jb(b,e,f).then(function(k){return h.fetchJson(k.xhrUrl,k.fetchOpt)}).then(function(k){return K(a.win,"xhr").xssiJson(k,g)}).then(function(k){if(null==k)throw Error("Response is undefined.");return fb(k,d||".")}).catch(function(k){throw C().createError("failed fetching JSON data",
k);})}
function jb(a,b,c){var d=a.getAttribute("src"),e=va(a,"url-replace");return(1<=b?e.expandUrlAsync(d):Promise.resolve(d)).then(function(f){if(1==b){var g=e.collectDisallowedVarsSync(a);if(0<g.length)throw C().createError('URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. Please add data-amp-replace="'+(g.join(" ")+'" to the <')+(a.tagName+"> element. See https://bit.ly/amp-var-subs."));}var h={};a.hasAttribute("credentials")&&(h.credentials=a.getAttribute("credentials"));c&&
(h.cache="reload");return{xhrUrl:f,fetchOpt:h}})};function kb(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a};function lb(a){a=AMP.BaseElement.call(this,a)||this;a.S=void 0;a.aa=new J;return a}q(lb,AMP.BaseElement);m=lb.prototype;m.getLayoutPriority=function(){return 1};m.isAlwaysFixed=function(){return!0};m.isLayoutSupported=function(){return!0};
m.buildCallback=function(){var a=this;Ra(this.element);this.element.setAttribute("aria-hidden","true");var b=this.element;b.hasAttribute("overridable")&&eb(b).then(function(c){c.addOverridableKey(b.getAttribute("id"))});this.parseAndUpdate();this.element.hasAttribute("src")&&mb(this,!0);this.registerAction("refresh",function(){E(a.element.hasAttribute("src"),'Can\'t refresh <amp-state> without "src" attribute.');mb(a,!1,!0)})};
m.mutatedAttributesCallback=function(a){if(this.getAmpDoc().hasBeenVisible())void 0!==a.src&&this.element.hasAttribute("src")&&mb(this,!1);else{var b=this.M();D().error(b,"ampdoc must be visible before mutation.")}};m.renderOutsideViewport=function(){return!0};m.parseAndUpdate=function(){return void 0===this.S&&(this.S=nb(this),null!==this.S)?ob(this,this.S,!0):T()};
function nb(a){var b=a.element.children;if(0==b.length)return null;var c=a.M();if(1!=b.length)return a.user().error(c,"Should contain exactly one <script> child."),null;var d=b[0];return Za(d)?gb(d.textContent,function(e){a.user().error(c,"Failed to parse state. Is it valid JSON?",e)}):(a.user().error(c,'State should be in a <script> tag with type="application/json".'),null)}
function pb(a,b,c){var d=a.element,e=a.getAmpDoc(),f=d.getAttribute("src");f=R(Ma(f)).origin===R(Ma(e.win.location)).origin||b?2:1;return ib(e,a.element,{urlReplacement:f,refresh:c}).catch(function(g){g=g?kb(a.win,"amp-state.error",H({response:g.response})):null;va(d,"action").trigger(d,"fetch-error",g,1)})}
function mb(a,b,c){b||(a.aa=new J);var d=a.aa;a.getAmpDoc().whenFirstVisible().then(function(){return pb(a,b,c)}).then(function(e){return ob(a,e,b)}).then(function(){return d.resolve()}).catch(function(e){d.resolve();throw e;})}m.getFetchingPromise=function(){return this.element.hasAttribute("src")?this.aa.promise:T()};
function ob(a,b,c){if(void 0===b||null===b)return T();var d=E(a.element.id,"<amp-state> must have an id.");return eb(a.element).then(function(e){var f=G();f[d]=b;e.setState(f,{skipEval:c,skipAmpState:!c})})}m.M=function(){return"<amp-state> "+(this.element.getAttribute("id")||"<unknown id>")};var tb=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function ub(a){for(var b=[],c;c=tb.exec(a);){var d=c[1],e=void 0,f=void 0;if(c[2]){var g=c[3].toLowerCase();if("w"==g)e=parseInt(c[2],10);else if("x"==g)f=parseFloat(c[2]);else continue}else f=1;b.push({url:d,width:e,dpr:f})}return new vb(b)}
function vb(a){E(0<a.length,"Srcset must have at least one source");this.O=a;for(var b=!1,c=!1,d=0;d<a.length;d++){var e=a[d];b=b||!!e.width;c=c||!!e.dpr}E(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?wb:xb);this.sa=b}
vb.prototype.select=function(a,b){if(this.sa){b*=a;a=this.O;for(var c=0,d=Infinity,e=Infinity,f=0;f<a.length;f++){var g=a[f].width,h=Math.abs(g-b);if(h<=1.1*d||1.2<b/e)c=f,d=h,e=g;else break}b=c}else{a=this.O;c=0;d=Infinity;for(e=0;e<a.length;e++)if(f=Math.abs(a[e].dpr-b),f<=d)c=e,d=f;else break;b=c}return this.O[b].url};vb.prototype.getUrls=function(){return this.O.map(function(a){return a.url})};
vb.prototype.stringify=function(a){for(var b=[],c=this.O,d=0;d<c.length;d++){var e=c[d],f=e.url;a&&(f=a(f));f=this.sa?f+(" "+e.width+"w"):f+(" "+e.dpr+"x");b.push(f)}return b.join(", ")};function wb(a,b){E(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function xb(a,b){E(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};var yb={"class":{denylistedValueRegex:"(^|\\W)i-amphtml-"},hidden:null,text:null},zb={width:null,height:null},Ab={"AMP-AUDIO":{album:null,artist:null,artwork:null,controlsList:null,loop:null,src:{allowedProtocols:{https:!0}},title:null},"AMP-AUTOCOMPLETE":{src:{allowedProtocols:{https:!0}}},"AMP-BASE-CAROUSEL":{"advance-count":null,"auto-advance-count":null,"auto-advance-interval":null,"auto-advance-loops":null,"auto-advance":null,horizontal:null,"initial-index":null,loop:null,"mixed-length":null,
"side-slide-count":null,slide:null,"snap-align":null,"snap-by":null,snap:null,"visible-count":null},"AMP-BRIGHTCOVE":{"data-account":null,"data-embed":null,"data-player":null,"data-player-id":null,"data-playlist-id":null,"data-video-id":null},"AMP-CAROUSEL":{slide:null},"AMP-DATE-PICKER":{max:null,min:null,src:{allowedProtocols:{https:!0}}},"AMP-GOOGLE-DOCUMENT-EMBED":{src:null,title:null},"AMP-IFRAME":{src:null,title:null},"AMP-IMG":{alt:null,attribution:null,src:{allowedProtocols:{data:!0,http:!0,
https:!0}},srcset:{alternativeName:"src"}},"AMP-LIGHTBOX":{open:null},"AMP-LIST":{src:{allowedProtocols:{https:!0}},state:null,"is-layout-container":null},"AMP-SELECTOR":{disabled:null,selected:null},"AMP-STATE":{src:{allowedProtocols:{https:!0}}},"AMP-TIMEAGO":{datetime:null,title:null},"AMP-TWITTER":{"data-tweetid":null},"AMP-VIDEO":{album:null,alt:null,artist:null,artwork:null,attribution:null,controls:null,controlslist:null,loop:null,poster:null,preload:null,src:{allowedProtocols:{https:!0}},
title:null},"AMP-YOUTUBE":{"data-videoid":null},A:{href:{allowedProtocols:{ftp:!0,geo:!0,http:!0,https:!0,mailto:!0,maps:!0,bip:!0,bbmi:!0,chrome:!0,"itms-services":!0,facetime:!0,"fb-me":!0,"fb-messenger":!0,intent:!0,line:!0,skype:!0,sms:!0,snapchat:!0,tel:!0,tg:!0,threema:!0,twitter:!0,viber:!0,webcal:!0,"web+mastodon":!0,wh:!0,whatsapp:!0}}},BUTTON:{disabled:null,type:null,value:null},DETAILS:{open:null},FIELDSET:{disabled:null},IMAGE:{"xlink:href":{allowedProtocols:{http:!0,https:!0}}},INPUT:{accept:null,
accesskey:null,autocomplete:null,checked:null,disabled:null,height:null,inputmode:null,max:null,maxlength:null,min:null,minlength:null,multiple:null,pattern:null,placeholder:null,readonly:null,required:null,selectiondirection:null,size:null,spellcheck:null,step:null,type:{denylistedValueRegex:"(^|\\s)(button|image|)(\\s|$)"},value:null,width:null},OPTION:{disabled:null,label:null,selected:null,value:null},OPTGROUP:{disabled:null,label:null},SECTION:{"data-expand":null,expanded:null},SELECT:{autofocus:null,
disabled:null,multiple:null,required:null,size:null},SOURCE:{src:{allowedProtocols:{https:!0}},type:null},TRACK:{label:null,src:{allowedProtocols:{https:!0}},srclang:null},TEXTAREA:{autocomplete:null,autofocus:null,cols:null,disabled:null,maxlength:null,minlength:null,pattern:null,placeholder:null,readonly:null,required:null,rows:null,selectiondirection:null,selectionend:null,selectionstart:null,spellcheck:null,wrap:null,defaulttext:null}},Bb={src:!0,srcset:!0,href:!0,"xlink:href":!0};
function Cb(a){this.ua=a}Cb.prototype.canBind=function(a,b){return void 0!==Db(this,a,b)};
Cb.prototype.isResultValid=function(a,b,c){var d=Db(this,a,b);d&&d.alternativeName&&(d=Db(this,a,d.alternativeName));if(void 0===d)return!1;if(null===d)return!0;if(c&&I(Bb,b)){if("srcset"===b){try{var e=ub(c)}catch(h){return C().error("amp-bind","Failed to parse srcset: ",h),!1}var f=e.getUrls()}else f=[c];for(a=0;a<f.length;a++){a:{e=f[a];b=d;if(e){if(/__amp_source_origin/.test(e)){b=!1;break a}if(b=b.allowedProtocols)if(e=/^([^:\/?#.]+):[\s\S]*$/.exec(e),null!==e&&(e=e[1].toLowerCase().trim(),!ta.call(b,
e))){b=!1;break a}}b=!0}if(!b)return!1}}var g=d.denylistedValueRegex;return c&&g&&(new RegExp(g,"i")).test(c)?!1:!0};function Db(a,b,c){if(c.startsWith("aria-"))return null;if(!I(Bb,c)||a.ua){var d=I(yb,c);if(void 0!==d)return d;var e=I(zb,c);if(b.startsWith("AMP-")&&void 0!==e)return e;var f=I(Ab,b);if(f)return f[c]}};var Eb=!1;function Fb(a){if(!Eb){Eb=!0;a=a.body;var b={opacity:1,visibility:"visible",animation:"none"},c;for(c in b){var d=a,e=b[c];var f=d.style;var g=c;if(g.startsWith("--"))f=g;else{Pa||(Pa=G());var h=Pa[g];if(!h){h=g;if(void 0===f[g]){var k=g;k=k.charAt(0).toUpperCase()+k.slice(1);b:{for(var l=0;l<Qa.length;l++){var p=Qa[l]+k;if(void 0!==f[p]){k=p;break b}}k=""}void 0!==f[k]&&(h=k)}Pa[g]=h}f=h}f&&(f.startsWith("--")?d.style.setProperty(f,e):d.style[f]=e)}}};function U(){this.o=[]}U.prototype.peek=function(){var a=this.o.length;return a?this.o[a-1].item:null};U.prototype.enqueue=function(a,b){if(isNaN(b))throw Error("Priority must not be NaN.");for(var c=-1,d=0,e=this.o.length;d<=e;){c=Math.floor((d+e)/2);if(c===this.o.length)break;if(this.o[c].priority<b)d=c+1;else if(0<c&&this.o[c-1].priority>=b)e=c-1;else break}this.o.splice(c,0,{item:a,priority:b})};U.prototype.forEach=function(a){for(var b=this.o.length;b--;)a(this.o[b].item)};
U.prototype.dequeue=function(){return this.o.length?this.o.pop().item:null};ca.Object.defineProperties(U.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.o.length}}});var Gb=/nochunking=1/.test(self.location.hash),Hb=T();function Ib(a,b){if(Gb)Hb.then(b);else{var c=Jb,d=N(a),e=O(d);xa(e,d,"chunk",c);M(a,"chunk").run(b,10)}}function V(a){this.state="not_run";this.Z=a}function Kb(a,b){if("run"!=a.state){a.state="run";try{a.Z(b)}catch(c){throw a.ma(),c;}}}V.prototype.M=function(){return this.Z.displayName||this.Z.name};V.prototype.ma=function(){};V.prototype.ka=function(){return!1};V.prototype.qa=function(){return!1};function W(a,b,c){V.call(this,a);this.ga=c}
q(W,V);W.prototype.ma=function(){Fb(self.document)};W.prototype.ka=function(){return this.ga.ampdoc.isVisible()};W.prototype.qa=function(){return this.ga.ha};
function Jb(a){var b=this;this.ampdoc=a;this.h=a.win;this.L=new U;this.fa=this.ia.bind(this);this.I=0;this.Ea=!(!this.h.navigator.scheduling||!this.h.navigator.scheduling.isInputPending);this.U=!1;this.va=this.h.document.documentElement.hasAttribute("i-amphtml-no-boilerplate");this.h.addEventListener("message",function(c){"amp-macro-task"==c.data&&b.ia(null)});this.ha=!1;ya(O(a),"viewer").then(function(){b.ha=!0});a.onVisibilityChanged(function(){a.isVisible()&&Lb(b)})}
Jb.prototype.run=function(a,b){var c=new V(a);this.L.enqueue(c,b);Lb(this)};Jb.prototype.runForStartup=function(a){a=new W(a,this.h,this);this.L.enqueue(a,Number.POSITIVE_INFINITY);Lb(this)};function Mb(a,b){for(var c=a.L.peek();c&&"not_run"!==c.state;)a.L.dequeue(),c=a.L.peek();c&&b&&a.L.dequeue();return c}
Jb.prototype.ia=function(a){var b=this,c=Mb(this,!0);if(!c)return this.U=!1,this.I=0,!1;try{var d=Date.now();Kb(c,a)}finally{Hb.then().then().then().then().then().then().then().then().then(function(){b.U=!1;b.I+=Date.now()-d;D().fine("CHUNK",c.M(),"Chunk duration",Date.now()-d,b.I);Lb(b)})}return!0};function Nb(a){a.va&&(a.Ea?a.h.navigator.scheduling.isInputPending():5<a.I)?(a.I=0,Ob(a)):Hb.then(function(){a.fa(null)})}
function Lb(a){if(!a.U){var b=Mb(a);b&&(b.ka()?(a.U=!0,Nb(a)):b.qa()&&a.h.requestIdleCallback?Pb(a.h,a.fa):Ob(a))}}function Ob(a){a.h.postMessage("amp-macro-task","*")}
function Pb(a,b){function c(e){if(15>e.timeRemaining()){var f=2E3-(Date.now()-d);0>=f||e.didTimeout?(D().fine("CHUNK","Timed out",2E3,e.didTimeout),b(e)):(D().fine("CHUNK","Rescheduling with",f,e.timeRemaining()),a.requestIdleCallback(c,{timeout:f}))}else D().fine("CHUNK","Running idle callback with ",15),b(e)}var d=Date.now();a.requestIdleCallback(c,{timeout:2E3})};function Qb(){this.F=G();this.j=null}m=Qb.prototype;m.get=function(a){a=this.F[a];return null==a?null:a};m.whenSignal=function(a){var b=this.j&&this.j[a];if(!b){var c=this.F[a];null!=c?b={promise:"number"==typeof c?Promise.resolve(c):Promise.reject(c)}:(c=new J,b={promise:c.promise,resolve:c.resolve,reject:c.reject});this.j||(this.j=G());this.j[a]=b}return b.promise};
m.signal=function(a,b){if(null==this.F[a]){var c=void 0==b?Date.now():b;this.F[a]=c;(a=this.j&&this.j[a])&&a.resolve&&(a.resolve(c),a.resolve=void 0,a.reject=void 0)}};m.rejectSignal=function(a,b){null==this.F[a]&&(this.F[a]=b,(a=this.j&&this.j[a])&&a.reject&&(a.reject(b),a.promise.catch(function(){}),a.resolve=void 0,a.reject=void 0))};m.reset=function(a){this.F[a]&&delete this.F[a];var b=this.j&&this.j[a];b&&!b.resolve&&delete this.j[a]};function Rb(a,b){function c(){d=0;var g=5E3-(a.Date.now()-e);if(0<g)d=a.setTimeout(c,g);else{var h=f;f=null;b.apply(null,h)}}var d=0,e=0,f=null;return function(g){for(var h=[],k=0;k<arguments.length;++k)h[k-0]=arguments[k];e=a.Date.now();f=h;d||(d=a.setTimeout(c,5E3))}};function Sb(a,b){for(var c=[],d=0,e=0;e<a.length;e++){var f=a[e];b(f,e,a)?c.push(f):(d<e&&(a[d]=f),d++)}d<a.length&&(a.length=d)}function Tb(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};function Ub(a){var b=this;this.h=a;this.Ga=K(a,"xhr");var c=ab();D().fine("web-worker","Fetching web worker from",c);this.da=null;this.ja=this.Ga.fetchText(c,{ampCors:!1,bypassInterceptorForDev:!1}).then(function(d){return d.text()}).then(function(d){d=d.replace(/^\/\/# sourceMappingURL=.*/,"//# sourceMappingURL="+(c+".map"));d=new a.Blob([d+"\n//# sourceurl="+c],{type:"text/javascript"});var e=a.URL.createObjectURL(d);b.da=new a.Worker(e);b.da.onmessage=b.Da.bind(b)});this.T={};this.xa=0;this.ta=
[a]}function Vb(a,b,c,d){return a.ja.then(function(){return new Promise(function(e,f){var g=a.xa++;a.T[g]={method:b,resolve:e,reject:f};e=d||a.h;f=a.ta.indexOf(e);e=0<=f?f:a.ta.push(e)-1;a.da.postMessage({method:b,args:c,scope:e,id:g})})})}Ub.prototype.Da=function(a){var b=a.data;a=b.method;var c=b.returnValue;b=b.id;var d=this.T[b];d?(d.resolve(c),delete this.T[b]):D().error("web-worker","Received unexpected message ("+a+", "+b+") from worker.")};
Ub.prototype.hasPendingMessages=function(){return 0<Object.keys(this.T).length};Ub.prototype.Ha=function(){return this.ja};function Wb(a){var b=a.documentElement;return["\u26a14email","amp4email"].some(function(c){return b.hasAttribute(c)})};function Xb(){var a=Yb();return function(b){return setTimeout(b,a())}}function Yb(){var a=0;return function(){var b=Math.pow(1.5,a++);var c=b*(c||.3)*Math.random();.5<Math.random()&&(c*=-1);b+=c;return 1E3*b}};var X=self.__AMP_ERRORS||[];self.__AMP_ERRORS=X;function Zb(a){Zb=Xb();return Zb(a)}function $b(a){try{return JSON.stringify(a)}catch(b){return String(a)}}var ac;
function Y(a,b){try{if(a)if(void 0!==a.message)a=qa(a);else{var c=a;a=Error($b(c));a.origError=c}else a=Error("Unknown error");if(!a.reported){a.reported=!0;var d=b||a.associatedElement;d&&d.classList&&(d.classList.add("i-amphtml-error"),r().development&&(d.classList.add("i-amphtml-element-error"),d.setAttribute("error-message",a.message)));if(self.console&&(0<=a.message.indexOf("\u200b\u200b\u200b")||!a.expected)){var e=console.error||console.log;a.messageArray?e.apply(console,a.messageArray):d?
e.call(console,a.message,d):e.call(console,a.message)}d&&d.Aa&&d.Aa("amp:error",a.message);bc.call(self,void 0,void 0,void 0,void 0,a)}}catch(f){setTimeout(function(){throw f;})}}function bc(a,b,c,d,e){var f=this;!this||!this.document||e&&e.expected||Fb(this.document);if(!r().development){var g=!1;try{g=cc()}catch(k){}if(!(g&&.01<Math.random())){var h=dc(a,b,c,d,e,g);h&&Zb(function(){try{return ec(f,h).catch(function(){})}catch(k){}})}}}
function ec(a,b){return b.pt&&.9>Math.random()?T():fc(a,b).then(function(c){if(!c){var d=new XMLHttpRequest;d.open("POST",.1>Math.random()?z.betaErrorReporting:z.errorReporting,!0);d.send(JSON.stringify(b))}})}
function fc(a,b){a=K(a,"ampdoc");if(!a.isSingleDoc())return Promise.resolve(!1);var c=a.getSingleDoc();if(!c.getRootNode().documentElement.hasAttribute("report-errors-to-viewer"))return Promise.resolve(!1);var d=M(c,"viewer");return d.hasCapability("errorReporter")?d.isTrustedViewer().then(function(e){if(!e)return!1;d.sendMessage("error",H({m:b.m,a:b.a,s:b.s,el:b.el,ex:b.ex,v:b.v,pt:b.pt,jse:b.jse}));return!0}):Promise.resolve(!1)}
function dc(a,b,c,d,e,f){var g=a;e&&(g=e.message?e.message:String(e));g||(g="Unknown error");a=g;var h=!(!e||!e.expected);if(!/_reported_/.test(a)&&"CANCELLED"!=a){var k=!(self&&self.window),l=Math.random();if(-1!=a.indexOf("Failed to load:")||"Script error."==a||k)if(h=!0,.001<l)return;var p=0<=a.indexOf("\u200b\u200b\u200b");if(!(p&&.1<l)){g=Object.create(null);g.v=r().rtvVersion;g.noAmp=f?"1":"0";g.m=a.replace("\u200b\u200b\u200b","");g.a=p?"1":"0";g.ex=h?"1":"0";g.dw=k?"1":"0";var n="1p";self.context&&
self.context.location?(g["3p"]="1",n="3p"):r().runtime&&(n=r().runtime);g.rt=n;"inabox"===n&&(g.adid=r().a4aId);f=self;g.ca=f.AMP_CONFIG&&f.AMP_CONFIG.canary?"1":"0";f=self;g.bt=f.AMP_CONFIG&&f.AMP_CONFIG.type?f.AMP_CONFIG.type:"unknown";self.location.ancestorOrigins&&self.location.ancestorOrigins[0]&&(g.or=self.location.ancestorOrigins[0]);self.viewerState&&(g.vs=self.viewerState);self.parent&&self.parent!=self&&(g.iem="1");if(self.AMP&&self.AMP.viewer){var t=self.AMP.viewer.getResolvedViewerUrl(),
B=self.AMP.viewer.maybeGetMessagingOrigin();t&&(g.rvu=t);B&&(g.mso=B)}ac||(ac=gc());g.jse=ac;var w=[];f=self.__AMP__EXPERIMENT_TOGGLES||null;for(var u in f)w.push(u+"="+(f[u]?"1":"0"));g.exps=w.join(",");e?(g.el=e.associatedElement?e.associatedElement.tagName:"u",e.args&&(g.args=JSON.stringify(e.args)),p||e.ignoreStack||!e.stack||(g.s=e.stack),e.message&&(e.message+=" _reported_")):(g.f=b||"",g.l=c||"",g.c=d||"");g.r=self.document?self.document.referrer:"";g.ae=X.join(",");g.fr=self.location.originalHash||
self.location.hash;"production"===g.bt&&(g.pt="1");b=a;25<=X.length&&X.splice(0,X.length-25+1);X.push(b);return g}}}function cc(){var a=self;if(!a.document)return!1;a=a.document.querySelectorAll("script[src]");for(var b=0;b<a.length;b++)if(!S(a[b].src.toLowerCase()))return!0;return!1}
function gc(){function a(){}a.prototype.t=function(){throw Error("message");};var b=new a;try{b.t()}catch(d){b=d.stack;if(b.startsWith("t@"))return"Safari";if(-1<b.indexOf(".prototype.t@"))return"Firefox";var c=b.split("\n").pop();if(/\bat .* \(/i.test(c))return"IE";if(b.startsWith("Error: message"))return"Chrome"}return"unknown"};function hc(a,b,c){var d=self.location;Oa(c);var e=S(d),f=R(Ma(d));if("href"==b&&!c.startsWith("#"))return Na(c,f);if("src"==b)return"amp-img"==a?ic(c,f,e):Na(c,f);if("srcset"==b){try{var g=ub(c)}catch(h){return C().error("URL-REWRITE","Failed to parse srcset: ",h),c}return g.stringify(function(h){return ic(h,f,e)})}return c}
function ic(a,b,c){a=R(Na(a,b));return"data:"==a.protocol||S(a)||!c?a.href:z.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};var jc=/^(i?-)?amp(html)?-/,kc={INPUT:{checked:!0,value:!0},OPTION:{selected:!0},TEXTAREA:{text:!0,disabled:!0}},lc=G({"AMP-CAROUSEL":["slide"],"AMP-LIST":["is-layout-container"],"AMP-SELECTOR":["selected"]}),mc=["AMP-LIST"];
function nc(a){var b=this;this.ampdoc=a;this.J=this.h=a.win;this.Y=[];this.Ba=Rb(this.h,function(){b.Y.length=0});this.H=[];this.D=G();this.$=M(a,"history");this.na=[];this.K=1E3;this.la=M(a,"mutator");this.B=G();this.Fa=L(this.h,"timer");this.ra=null;this.W=M(this.ampdoc,"viewer");this.W.onMessageRespond("premutate",this.Ca.bind(this));this.oa=a.whenFirstVisible().then(function(){return a.whenReady().then(function(){return a.getRootNode()})});this.N=this.oa.then(function(d){return oc(b,d)});this.ea=
new J;this.V=null;this.pa=new Qb;var c=self.AMP;c.printState=c.printState||this.za.bind(this);c.setState=c.setState||function(d){return b.setState(d)};c.eval=c.eval||this.ya.bind(this)}m=nc.prototype;m.signals=function(){return this.pa};
m.setState=function(a,b){var c=this,d=b=void 0===b?{}:b;D().info("amp-bind","setState (init=%s):",d.skipEval,a);try{ua(this.B,a)}catch(e){C().error("amp-bind","Failed to merge result from AMP.setState().",e)}return d.skipEval?T():this.V=this.N.then(function(){return pc(c)}).then(function(e){return qc(c,e,{skipAmpState:d.skipAmpState,constrain:d.constrain})})};
m.invoke=function(a){var b=a.args,c=a.event,d=a.method,e=a.sequenceId,f=a.tagOrTarget;if(this.Y.includes(e))return C().error("amp-bind","One state action allowed per event."),T();this.Y.push(e);this.Ba();if(b=b.__AMP_OBJECT_STRING__){this.K=Math.min(2E3,Math.max(1E3,this.K+500));this.pa.signal("FIRST_MUTATE");var g={};c&&c.detail&&(g.event=c.detail);switch(d){case "setState":return this.setStateWithExpression(b,g);case "pushState":return this.pushStateWithExpression(b,g);default:return Promise.reject(D().createError("Unrecognized method: %s.%s",
f,d))}}else C().error("AMP-BIND","Please use the object-literal syntax, e.g. \"AMP.setState({foo: 'bar'})\" instead of \"AMP.setState(foo='bar')\".");return T()};m.setStateWithExpression=function(a,b){var c=this;return rc(this,a,b).then(function(d){return sc(c,d)})};m.setStateWithObject=function(a){return(a=tc(a))?sc(this,a):Promise.reject("Invalid state")};
function sc(a,b){D().info("amp-bind","setState:",b);a.V=a.setState(b).then(function(){return uc(a)}).then(function(c){c&&a.$.replace(c)});return a.V}m.pushStateWithExpression=function(a,b){var c=this;D().info("amp-bind","pushState:",a);return rc(this,a,b).then(function(d){function e(){return c.setState(f)}var f=G();Object.keys(d).forEach(function(g){f[g]=tc(c.B[g])});return c.setState(d).then(function(){return uc(c)}).then(function(g){c.$.push(e,g)})})};
function uc(a){var b=H({data:H({"amp-bind":a.B}),title:a.J.document.title});return a.W.isEmbedded()?a.W.isTrustedViewer().then(function(c){return c?b:null}):Promise.resolve(b)}m.rescan=function(a,b,c){var d=this,e=c=void 0===c?{}:c;return(e.fast?this.ea.promise:this.N).then(function(){return d.Fa.timeoutPromise(e.timeout||2E3,vc(d,a,b,e),"Timed out waiting for amp-bind to rescan.")})};
function vc(a,b,c,d){D().info("amp-bind","rescan: ",b,c,d);return(d.fast?wc(a,b,c):xc(a,b,c)).then(function(){if(d.update)return pc(a).then(function(e){return qc(a,e,{constrain:b,evaluateOnly:"evaluate"===d.update})})})}
function wc(a,b,c){var d=yc(a,c),e=[],f=b.filter(function(h){return h.hasAttribute("i-amphtml-binding")});b.forEach(function(h){h=h.querySelectorAll("[i-amphtml-binding]");Array.prototype.push.apply(f,h)});var g=a.K-a.numberOfBindings();for(b=0;b<f.length&&!zc(a,f[b],g-e.length,e);b++);d.then(function(h){D().info("amp-bind","rescan.fast: delta=%s, total=%s",e.length-h,a.numberOfBindings())});return 0<e.length?Ac(a,e):T()}
m.getState=function(a){a=a?fb(this.B,a):void 0;return x(a)||Array.isArray(a)?tc(a):a};m.getStateAsync=function(a){var b=this,c=/^[^.]*/.exec(a)[0];return this.oa.then(function(d){var e=d.querySelector("#"+String(c).replace(Ua,Va));if(!e)throw Error("#"+c+" does not exist.");return $a(e).then(function(f){return f.getImpl(!0)}).then(function(f){return f.getFetchingPromise()}).catch(function(){}).then(function(){return b.getState(a)})})};
m.getStateValue=function(a){a=fb(this.B,a);return void 0===a||null===a?null:x(a)||Array.isArray(a)?JSON.stringify(a):String(a)};
function oc(a,b){var c=!Wb(a.J.document);a.ra=new Cb(c);return Z(a,"bind.init",[c]).then(function(){return Promise.all([Bc(a).then(function(){return a.ea.resolve()}),Cc(a,[b])])}).then(function(){b.addEventListener("amp:dom-update",function(d){return Dc(a,d)})}).then(function(){var d=b.querySelectorAll("AMP-STATE"),e=v(d).map(function(f){return $a(f).then(function(){return f.getImpl(!1)}).then(function(g){return g.parseAndUpdate()})});return Promise.all(e)}).then(function(){a.W.sendMessage("bindReady",
void 0);if(r().development)return pc(a).then(function(d){return Ec(a,d)})})}m.numberOfBindings=function(){return this.H.reduce(function(a,b){return a+b.boundProperties.length},0)};m.Ka=function(a){this.K=a};m.Ia=function(){return this.$};
m.Ca=function(a){var b=this,c=[];return this.N.then(function(){Object.keys(a.state).forEach(function(d){b.na.includes(d)||(delete a.state[d],c.push(d))});0<c.length&&C().warn("amp-bind","Some state keys could not be premutated because they are missing the overridable attribute: "+c.join(", "));return b.setState(a.state)})};m.addOverridableKey=function(a){this.na.push(a)};
function Bc(a){var b=a.ampdoc.getBody().querySelectorAll("AMP-BIND-MACRO"),c=[];Ya(b,function(d){var e=(d.getAttribute("arguments")||"").split(",").map(function(f){return f.trim()});c.push({id:d.getAttribute("id"),argumentNames:e,expressionString:d.getAttribute("expression")})});return 0==c.length?Promise.resolve(0):Z(a,"bind.addMacros",[c]).then(function(d){d.forEach(function(e,f){Fc(e,"amp-bind: Parsing amp-bind-macro failed.",b[f])});return c.length})}
function Cc(a,b){if(!b.length)return Promise.resolve(0);var c=b.map(function(d){var e=a.K-a.numberOfBindings();return Gc(a,d,e).then(function(f){var g=f.bindings;f.limitExceeded&&D().expectedError("amp-bind","Maximum number of bindings reached (%s). Additional elements with bindings will be ignored.",a.K);return g})});return Promise.all(c).then(function(d){d=Array.prototype.concat.apply([],d);return 0<d.length?Ac(a,d):0})}
function Ac(a,b){return Z(a,"bind.addBindings",[b]).then(function(c){Object.keys(c).forEach(function(d){var e=a.D[d];0<e.length&&Fc(c[d],'amp-bind: Expression compile error in "'+d+'".',e[0])});return b.length})}
function yc(a,b){if(!b.length)return Promise.resolve(0);Sb(a.H,function(g){for(var h=0;h<b.length;h++)if(b[h].contains(g.element))return!0;return!1});var c=[],d;for(d in a.D){var e=a.D[d];Sb(e,function(g){for(var h=0;h<b.length;h++)if(b[h].contains(g))return!0;return!1});0==e.length&&(c.push(d),delete a.D[d])}var f=c.length;return 0<f?Z(a,"bind.removeBindingsWithExpressionStrings",[c]).then(function(){return f}):Promise.resolve(0)}
function Gc(a,b,c){function d(){var h=f.currentNode;if(!h)return!0;if(h.nodeType!==Node.ELEMENT_NODE)return!f.nextNode();zc(a,h,c-e.length,e)&&(g=!0);if(mc.includes(h.nodeName))a:{for(h=f.currentNode;h;h=f.parentNode())if(h=f.nextSibling())break a;h=null}else h=f.nextNode();return!h||g}var e=[],f=(b.nodeType==Node.DOCUMENT_NODE?b:b.ownerDocument).createTreeWalker(b,NodeFilter.SHOW_ELEMENT,null,!1),g=!1;return new Promise(function(h){function k(l){var p=!1;if(l&&!l.didTimeout)for(;1<l.timeRemaining()&&
!p;)p=d();else for(l=0;250>l&&!p;l++)p=d();p?h({bindings:e,limitExceeded:g}):Ib(a.ampdoc,k)}Ib(a.ampdoc,k)})}function zc(a,b,c,d){var e=!1,f=Hc(a,b);f.length>c&&(f.length=c,e=!0);0<f.length&&a.H.push({element:b,boundProperties:f});var g=b.tagName;f.forEach(function(h){var k=h.expressionString;d.push({tagName:g,property:h.property,expressionString:k});a.D[k]||(a.D[k]=[]);a.D[k].push(b)});return e}
function Hc(a,b){for(var c=[],d=b.attributes,e=0,f=d.length;e<f;e++){a:{var g=void 0,h=a,k=d[e];var l=b;var p=l.tagName,n=k.name;if(2<n.length&&"["===n[0]&&"]"===n[n.length-1])g=n.substr(1,n.length-2);else if(n.startsWith("data-amp-bind-")&&(g=n.substr(14),l.hasAttribute("["+g+"]"))){l=null;break a}if(g){if(h.ra.canBind(p,g)){l={property:g,expressionString:k.value};break a}g=C().createError("%s: Binding to [%s] on <%s> is not allowed.","amp-bind",g,p);Y(g,l)}l=null}l&&c.push(l)}return c}
function rc(a,b,c){return a.N.then(function(){Object.assign(c,a.B);return Z(a,"bind.evaluateExpression",[b,c])}).then(function(d){var e=d.result;if(d=d.error)throw Fc(d,"amp-bind: Expression eval failed.");return e})}
function pc(a){return Z(a,"bind.evaluateBindings",[a.B]).then(function(b){var c=b.results,d=b.errors;Object.keys(d).forEach(function(e){var f=a.D[e];if(0<f.length){var g=d[e],h=C().createError('%s: Expression evaluation error in "%s". %s',"amp-bind",e,g.message);h.stack=g.stack;Y(h,f[0])}});D().info("amp-bind","evaluation:",c);return c})}
function Ec(a,b){var c=void 0===c?!0:c;var d={};a.H.forEach(function(e){var f=e.element;e.boundProperties.forEach(function(g){var h=b[g.expressionString];if(void 0!==h){var k=g.property,l=lc[f.tagName];if(l&&l.includes(k))h=null;else{switch(k){case "text":k=f.textContent;h=String(h);l=k.trim()===h.trim();break;case "class":k=[];for(l=0;l<f.classList.length;l++){var p=f.classList[l];jc.test(p)||k.push(p)}p=[];Array.isArray(h)?p=h:"string"===typeof h?(l=h.trim(),0<l.length&&(p=l.split(" "))):(l=C().createError('%s: "%s" is not a valid result for [class].',
"amp-bind",h),Y(l,f));b:{l=k;var n=p;if(l.length!==n.length)l=!1;else{p=(Array.isArray(l)?l:v(l)).sort();n=(Array.isArray(n)?n:v(n)).sort();for(var t=0;t<l.length;t++)if(p[t]!==n[t]){l=!1;break b}l=!0}}break;default:k=f.getAttribute(k),l=!0===h?""===k:!1===h?null===k:"number"===typeof h?Number(k)===h:k===h}h=l?null:{expected:h,actual:k}}var B=h;if(B){h=f.tagName;k=g.property;g=g.expressionString;l=B.expected;var w=B.actual;d[h+"["+k+"]"+l+":"+w]=!0;c&&C().warn("amp-bind","Default value ("+w+") does not match first result ("+
(l+") for <"+h+" ["+k+']="')+(g+'">. We recommend writing expressions with matching default values, but this can be safely ignored if intentional.'))}}})});return Object.keys(d)}function Ic(a,b){var c=[];a.forEach(function(d){var e=d.previousResult,f=b[d.expressionString];void 0===f||hb(f,e)||(d.previousResult=f,c.push({boundProperty:d,newValue:f}))});return c}
function qc(a,b,c){var d=[];a.H.forEach(function(e){if(!c.skipAmpState||"AMP-STATE"!==e.element.tagName)if(!c.constrain||c.constrain.some(function(h){return h.contains(e.element)})){var f=e.element,g=Ic(e.boundProperties,b);c.evaluateOnly||d.push(Jc(a,f,g))}});return Promise.all(d)}
function Jc(a,b,c){return 0===c.length?T():a.la.mutateElement(b,function(){var d=G(),e,f;c.forEach(function(h){var k=h.boundProperty,l=h.newValue,p=k.property;a:{k=k.property;var n=b.tagName;switch(k){case "defaulttext":b.textContent=String(l);break;case "text":k=String(l);"TITLE"===n&&b.parentNode===a.J.document.head&&(a.J.document.title=k);"TEXTAREA"===n?b.value=k:b.textContent=k;break;case "class":k=[];for(n=0;n<b.classList.length;n++){var t=b.classList[n];jc.test(t)&&k.push(t)}Array.isArray(l)||
"string"===typeof l?b.setAttribute("class",k.concat(l).join(" ")):null===l?b.setAttribute("class",k.join(" ")):(k=C().createError('%s: "%s" is not a valid result for [class].',"amp-bind",l),Y(k,b));break;default:var B="INPUT"===n&&k in b,w=b.getAttribute(k);n=!1;if("boolean"===typeof l){if(B&&b[k]!==l&&(b[k]=l,n=!0),l&&""!==w?(b.setAttribute(k,""),n=!0):l||null===w||(b.removeAttribute(k),n=!0),n&&"OPTION"===b.tagName&&"selected"===k&&l&&K(a.h,"platform").isSafari()&&(t=Xa(b,"select"))){var u=v(t.options).indexOf(b);
0<=u&&(t.selectedIndex=u)}}else if("object"===typeof l&&null!==l)n=!0;else if(l!==w)b:{w=String(l);try{t=b.tagName.toLowerCase();u=k.toLowerCase();var Da="src"==u||"href"==u||"xlink:href"==u||"srcset"==u?hc(t,u,w):w;if(S(self.location)&&"a"===t&&"href"===u){var qb=b.getAttribute(u),rb="#"===Da[0],sb=qb&&"#"===qb[0];rb&&!sb?(b.__AMP_ORIGINAL_TARGET_VALUE_||(b.__AMP_ORIGINAL_TARGET_VALUE_=b.getAttribute("target")),b.removeAttribute("target")):sb&&!rb&&b.setAttribute("target",b.__AMP_ORIGINAL_TARGET_VALUE_||
"_top")}B&&(b[u]=Da);b.setAttribute(u,Da);n=!0;break b}catch(Kc){n=C().createError('%s: "%s" is not a valid result for [%]',"amp-bind",w,k,Kc),Y(n,b)}n=!1}if(n){k={name:k,value:l};break a}}k=null}var Ea=k;Ea&&(d[Ea.name]=Ea.value,"width"==p?e="number"===typeof l&&isFinite(l)?Number(l):e:"height"==p&&(f="number"===typeof l&&isFinite(l)?Number(l):f));(l=kc[b.tagName])&&l[p]&&(p="OPTION"===b.tagName?Xa(b,"SELECT"):b)&&(l=kb(a.J,"amp:form-value-change",null,{bubbles:!0}),p.dispatchEvent(l))});void 0===
e&&void 0===f||a.la.forceChangeSize(b,f,e);if("function"===typeof b.mutatedAttributesCallback)try{b.mutatedAttributesCallback(d)}catch(h){var g=C().createError("%s: Applying expression results (%s) failed with error,","amp-bind",JSON.stringify(d),h);Y(g,b)}})}function Dc(a,b){b=b.target;var c=b.parentNode;c&&mc.includes(c.nodeName)||(D().info("amp-bind","dom_update:",b),xc(a,[b],[b],"dom_update.end").then(function(){}))}
function xc(a,b,c,d){var e=void 0===d?"rescan.slow":d,f=0;return yc(a,c).then(function(g){f=g;return Cc(a,b)}).then(function(g){D().info("amp-bind","%s: delta=%s, total=%s",e,g-f,a.numberOfBindings())})}function Z(a,b,c){var d=a.h;a=a.J;if(d.Worker){var e=d;e=e.__AMP_TOP||(e.__AMP_TOP=e);xa(e,e,"amp-worker",Ub);b=Vb(K(d,"amp-worker"),b,c||[],a)}else b=Promise.reject("Worker not supported in window.");return b}
function Fc(a,b,c){b=C().createError("%s %s",b,a.message);b.stack=a.stack;Y(b,c);return b}function tc(a){if(void 0===a)return null;try{return JSON.parse(JSON.stringify(a))}catch(b){D().error("amp-bind","Failed to copy JSON ("+a+") with error: "+b)}return null}
m.za=function(a){if(a)if("string"==typeof a){var b=fb(this.B,a);C().info("amp-bind",b)}else a.nodeType==Node.ELEMENT_NODE?(b=C().assertElement(a),Lc(this,b)):C().info("amp-bind",'Invalid argument. Pass a JSON expression or an element instead e.g. AMP.printState("foo.bar") or AMP.printState($0) after selecting an element.');else C().info("amp-bind",this.B)};
function Lc(a,b){var c=Tb(a.H,function(f){return f.element==b});if(0>c)C().info("amp-bind","Element has no bindings:",b);else{var d=[],e=a.H[c].boundProperties;e.forEach(function(f){d.push(rc(a,f.expressionString,a.B))});Promise.all(d).then(function(f){var g=G();e.forEach(function(h,k){g[h.property]=f[k]});C().info("amp-bind",g)})}}m.ya=function(a){rc(this,a,this.B).then(function(b){C().info("amp-bind",b)})};m.Ja=function(){return this.N};m.La=function(){return this.V};(function(a){a.registerServiceForDoc("bind",nc);a.registerElement("amp-state",lb);a.registerElement("amp-bind-macro",Sa)})(self.AMP);
})});

//# sourceMappingURL=amp-bind-0.1.js.map
